### ISSUE TITLE
请问readme中的PCB展示图是用什么软件制作的？

### ISSUE THREAD

**Issue by PeterSun01** [KitSprout/SmartIMU-Nano#1]
如题，图片链接如下，谢谢！https://camo.githubusercontent.com/5839ac1d0dc35e9e6b08282bf34c55afd2691c46bed752726a25af4c9418e63d/68747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f6c6963784a7378525475544c6e505a5a6c6f667853305a4d7172764271597675412d46714844487866384f713656557759436b327579416b7232327a3745774864657579416e41536f636e35764d3775497443415a6935533377576852554673475a4d596e5a72516965776b7067426337535f2d7064364e4672764848547a797a4c4145644935376e424f4b527a786f2d7356376e4c5a764c757935644470386b57417835473949796c623262725a466379483366354963443459373865616838396a426949516662364f6d68635f2d61536a6855587a42326876497741466a3374685133625a7351572d394a697931724e44514b536e6d776d593349426d43547169555f564154643675712d5a34525731573137785238384c323251584c6350697951734b655465356551426c787a756a6d6d4f49706e7931506c44656c67654736505139656c63467071476c5350694b6d456d4d6c355151597274667175687469346c586f505769617674516b7667335a6c463959785936524166336448514e684f45723867635963376d3674637a6d6479356c5459304636506744415a58565678626e4e575871364e2d51567241454b507365774750346d673137412d4d6f4875725644355079437649386c2d4d585768325f577667556b747671616e42356a7136396d5f75556a447473376f34554973584b7068506c4654537072375137536a34427072504f734246383974362d5a4a627132567532576d5a7343623675734250584c4d5632453548462d74674f41726533584d774b375962335273663633373d773832302d683634302d6e6f

**Comment by hom-wang** [comment]
@PeterSun01 以 Altium PCB 為基底，在 Power Point 上面加入方框後製，不是直接產生的
